# Natural Language Processing Day 7 

# Word Embedding Theory

In [1]:
# the concept of Word Embedding uses the concept of one hot representation 

# in the concept of one hot representation we usually convert a word in the form of vector on the basis of some feature

In [2]:
# In keras we have a library called as  one-hot which will try to convert a word in a vector based on the vocablury size

In [3]:
# eg after one_hot representation 

# Boy is Good will be --> [2000,4000,5000]

# where 2000 , 4000 , 5000 are the index numbers

In [4]:
# we will pass the whole value with the embedding layer

# embedding layer main task is to convert these words into some vector representation

# in the embedding layer we need to pass the number of dimenions

# Libraries used

In [5]:
#tensorflow > 2.0
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
# creating a sentence

sentences = ['This is Arsh Mishra',
            'This is Divyansh Sinha',
            'Both are cool ',
            'Lets hope for the best',
            'Bye Friends see u next time']

In [7]:
print(sentences)

['This is Arsh Mishra', 'This is Divyansh Sinha', 'Both are cool ', 'Lets hope for the best', 'Bye Friends see u next time']


In [8]:
# initializing the vocablury size
vocab_size = 10000

In [9]:
# one hot representation

In [11]:
onehot_representation = [one_hot(word,vocab_size) for word in sentences]

In [12]:
print(onehot_representation)

[[8758, 9614, 4933, 8191], [8758, 9614, 4244, 2940], [8512, 3836, 4381], [6597, 9583, 269, 8967, 7404], [8250, 286, 7148, 322, 3380, 5745]]


In [13]:
# here we are watching the one hot representation of each word

In [18]:
# word embedding representation

#importing the libraries for the above

from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [19]:
import numpy as np

In [20]:
# whenever we want to pass anything to the embedding layers then all the sentences should have the same number of words

In [21]:
# so for that we are using the pad - sequences

In [22]:
sentence_length = 10
embedding_docs = pad_sequences(onehot_representation,padding='pre',maxlen = sentence_length)

In [23]:
print(embedding_docs)

[[   0    0    0    0    0    0 8758 9614 4933 8191]
 [   0    0    0    0    0    0 8758 9614 4244 2940]
 [   0    0    0    0    0    0    0 8512 3836 4381]
 [   0    0    0    0    0 6597 9583  269 8967 7404]
 [   0    0    0    0 8250  286 7148  322 3380 5745]]


In [24]:
# here as we can see that the first sentece was this is arsh mishra and the second sentence was this is divyansh sinha
# this is -> both words are having the same value in the vectors representation

In [26]:
# initializing the dimensions
dimension = 15
model = Sequential()
model.add(Embedding(vocab_size,dimension,input_length = sentence_length))

In [27]:
model.compile('adam','mse')

In [28]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 10, 15)            150000    
Total params: 150,000
Trainable params: 150,000
Non-trainable params: 0
_________________________________________________________________


In [30]:
print(model.predict(embedding_docs))

[[[-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177
    0.01538659 -0.0312767  -0.00828079  0.01333589  0.01900805
   -0.01590142 -0.02361814 -0.0188328   0.01864443  0.01773231]
  [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177
    0.01538659 -0.0312767  -0.00828079  0.01333589  0.01900805
   -0.01590142 -0.02361814 -0.0188328   0.01864443  0.01773231]
  [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177
    0.01538659 -0.0312767  -0.00828079  0.01333589  0.01900805
   -0.01590142 -0.02361814 -0.0188328   0.01864443  0.01773231]
  [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177
    0.01538659 -0.0312767  -0.00828079  0.01333589  0.01900805
   -0.01590142 -0.02361814 -0.0188328   0.01864443  0.01773231]
  [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177
    0.01538659 -0.0312767  -0.00828079  0.01333589  0.01900805
   -0.01590142 -0.02361814 -0.0188328   0.01864443  0.01773231]
  [-0.01682502 -0.00459906  0.02913715  0.03771733

In [31]:
print(model.predict(embedding_docs)[0])

[[-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177  0.01538659
  -0.0312767  -0.00828079  0.01333589  0.01900805 -0.01590142 -0.02361814
  -0.0188328   0.01864443  0.01773231]
 [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177  0.01538659
  -0.0312767  -0.00828079  0.01333589  0.01900805 -0.01590142 -0.02361814
  -0.0188328   0.01864443  0.01773231]
 [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177  0.01538659
  -0.0312767  -0.00828079  0.01333589  0.01900805 -0.01590142 -0.02361814
  -0.0188328   0.01864443  0.01773231]
 [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177  0.01538659
  -0.0312767  -0.00828079  0.01333589  0.01900805 -0.01590142 -0.02361814
  -0.0188328   0.01864443  0.01773231]
 [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177  0.01538659
  -0.0312767  -0.00828079  0.01333589  0.01900805 -0.01590142 -0.02361814
  -0.0188328   0.01864443  0.01773231]
 [-0.01682502 -0.00459906  0.02913715  0.03771733 -0.02473177  0.

In [32]:
embedding_docs[0]

array([   0,    0,    0,    0,    0,    0, 8758, 9614, 4933, 8191])

In [33]:
# for each word we can see a vector assigned to it